Employees and Profile gravatars
RTUITLab/ITLab-Android pull request #26
Opened 2022-07-10 21:14 UTC by MrApple100

2022-07-11 09:05 UTC, CalamityDeadshot commented
Во-первых, Picasso, как и любая другая библиотека резолва картинок из сети, имеет статус view-layer helper'а, то есть живёт и используется на уровне View. Решение поместить логику резолва в репозиторий мне совершенно непонятно.   
Во-вторых, почему Picasso? Он создан для View-системы, а не для компоуза, соответственно тебе пришлось городить этот костыль через половину приложения, усложняя перевод DTO юзера в объекты UI.  
Для Picasso есть [расширение для Compose](https://github.com/square/picasso/tree/master/picasso-compose), которое на самом деле обёртка для его `RequestCreator`а, так что производительность этого сомнительная. Есть прекрасные альтернативы типа [Coil](https://coil-kt.github.io/coil/compose/) с удобным интерфейсом и кучей кастомизаций. Я советую использовать его.

2022-07-11 17:41 UTC, MrApple100 reviewed
Прочитал. Понял. Сделал с coil.
Изначально, когда как раз я засовывал bitmap в Dto, хотелось оптимизировать(убрать полностью) количество использований сторонней библиотеки во view. И чтобы не было ссылок на граватар, и всяких настроек (buildConfig) там же, потому что мне показалось, что это все таки, какая никакая часть архитектуры, хоть и сторонней библиотеки. Вот такая была моя логика.

2022-07-13 13:00 UTC, CalamityDeadshot requested changes

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/repository/UsersRepository.kt
> +
Зачем ты вставил поле пикассо между полем потока юзеров и его джавадоком? Теперь этот джавадок применяется к твоему полю и не отражает действительности.

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/repository/UsersRepository.kt
> +	}
Это стоит сделать методом расширения на строку - удобнее, красивее, и этому нечего делать в репозитории.

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/repository/UsersRepository.kt
> +		}
Почему ты блокируешь поток IO-диспетчера? `runBlocking` в принципе вообще не стоит использовать для дорогих операций, типа загрузки картинки. Кроме того, ты уверен, что Пикассовский `RequestCreator` не асинхронный по дефолту?

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/utils/GravatarGetter.kt
> +}
Не стоит спавнить классы-утилиты, если их задачи можно распределить по уже существующим классам. Я настоятельно рекомендую делегировать эту логику в DTO и класс `User` следующим образом:  
Во-первых, метод хэширования навесить на строку расширением, это более общая форма, никуда не инкапсулированная и возможно пригодящаяся в будущем:
```kotlin
fun String.toMd5() =
	MessageDigest.getInstance("MD5").digest(this.toByteArray())
		.joinToString("") { "%02x".format(it) }
```
Во-вторых, URL аватарки - релевантная для UI информация, поэтому она должна находиться в классе `User`:
```kotlin
// class UserResponse...
    fun toUser() = User(
        id = id,
        firstName = firstName,
        lastName = lastName,
        middleName = middleName,
        phoneNumber = phoneNumber,
        email = email,
        vkId = properties.firstOrNull { it.userPropertyType.title == "VKID" }?.value,
        group = properties.firstOrNull { it.userPropertyType.title == "Учебная группа" }?.value,
        skypeId = properties.firstOrNull { it.userPropertyType.title == "Skype" }?.value,
        properties = properties,
        gravatarUrl = BuildConfig.GRAVATAR_URI + email?.toMd5()
    )

// class User...

        // Делегируем получение размера классу UI
	fun getAvatarWithSize(size: Int) =
		"$gravatarUrl?s=$size"
```

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/utils/GravatarGetter.kt
> +}
Соответственно получение URL в UI будет выглядеть так:
```kotlin
                AsyncImage(
                    modifier = Modifier
                        .clip(RoundedCornerShape(10.dp))
                        .width(150.dp)
                        .height(150.dp),
                    model = ImageRequest.Builder(LocalContext.current)
                        .data(user.getAvatarWithSize(800))
                        .crossfade(true)
                        .build(),
                    placeholder = painterResource(R.drawable.ic_itlab),
                    contentScale = ContentScale.FillBounds,
                    contentDescription = stringResource(R.string.description)
                )
```

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/employees/Employee.kt
>  					)
Форматирование

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +	val gravatar:Bitmap? = null
Забыл удалить поле битмапа

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/repository/UsersRepository.kt
> +
Если в какой-то момент ты удаляешь весь написанный код в файле, роллбэкай его в состояние **до** изменений. Вот этот код меня удручает очень сильно, как и добавление пустых строк в этот же файл.

2022-07-13 13:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/employees/components/EmployeeCard.kt
> +	employeesViewModel: EmployeesViewModel = singletonViewModel()
Вью модель тут не используется и подсвечивается серым в IDE. Убирай пожалуйста такие вещи.

2022-07-13 13:04 UTC, MrApple100 commented on app/src/main/java/ru/rtuitlab/itlab/data/repository/UsersRepository.kt
> +		}
Он по дефолту требовал засунуть его в отличный от основного поток

2022-07-13 15:49 UTC, MrApple100 commented
Исправлены замечания, убраны пробелы и заформатировано

2022-07-13 16:26 UTC, CalamityDeadshot reviewed
Ничего критичного я не вижу, реагировать на комменты или нет - решай сам, мерджить можно.

2022-07-13 16:26 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Ну почему ты так не любишь пробелы и отформатированный по гайдлайнам код? Давай держать кодовую базу красивой и в чистоте.
Кроме того, расширению хэширования не место в `UserResponse`, этот метод намного более общий. Создай, например, в common/extensions файл String.kt, и туда пойдут все неспецифичные расширения на строку.

2022-07-13 16:26 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +	val gravatarUrl:String? = null
Привыкни пожалуйста смотреть на то, как это уже написано, и писать так же.

2022-07-13 16:26 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/employees/Employee.kt
> +                    )
Запятая после последнего аргумента не позволяют форматироващику на `Ctrl+Alt+L` правильно поставить скобку `AsyncImage`. Их тоже стоит убирать.

2022-07-13 16:26 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +	val gravatarUrl:String? = null
А почему URL nullable-то? Для него можно использовать то же выражение, что и в `toUser`.

2022-07-13 17:30 UTC, merged

2022-07-14 08:50 UTC, CAPCHIK commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Предлагаю вам в CI добавить линтер, чтобы падало, если что-то не так

2022-07-14 08:50 UTC, CAPCHIK commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
@CalamityDeadshot

2022-07-14 09:00 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Окей. Написал Никите.

2022-07-14 09:02 UTC, CAPCHIK commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Так а сам линтер, то, как его запускать - надо знать тебе, и ему ты по идее должен просто написать какую команду выполнять

Так что сначала настраиваешь его, запускаешь терминалом, и потом просишь его добавить выполнение этого шага, либо сам можешь добавить, помнится там ничего сверх сложного нет, чтобы просто bash  выполнить

2022-07-14 09:04 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Я наверное тогда это gradle-таском сделаю, чтобы на каждый билд работало, и ничего не надо было прописывать

2022-07-14 09:10 UTC, CAPCHIK commented on app/src/main/java/ru/rtuitlab/itlab/data/remote/api/users/models/UserResponse.kt
> +
Да, это идеальный вариант