Equipments to MD3
RTUITLab/ITLab-Android pull request #30
Opened 2022-12-11 16:01 UTC by MrApple100

2022-12-12 18:45 UTC, CalamityDeadshot requested changes
Кроме прочего, стоит исправить ошибки, которые ты сделал когда только начинал и не был знаком с Compose. Например, вместо текста с модификатором `clickable` нужно использовать семантически верные компоненты, например кнопку. Иначе кринж
![image](https://user-images.githubusercontent.com/44675043/207126992-093c9807-4825-471b-860a-110b666b0d0b.png)
![image](https://user-images.githubusercontent.com/44675043/207127092-69562082-ddfe-4282-990f-36c372f08e4f.png)

Вместо `Icon` с модификатором `clickable` нужно обернуть иконки в `IconButton`
![image](https://user-images.githubusercontent.com/44675043/207127608-f634440d-1877-4855-a7af-139d7018a6b2.png)
![image](https://user-images.githubusercontent.com/44675043/207127665-b6b341fc-c7af-41ed-8884-b9fe0272ff9a.png)

Для вот таких штук есть отдельный компонент - `IconizedRow`. Он в этом приложении всеобъемлющ, для этого и был написан. Стоит использовать его.
![image](https://user-images.githubusercontent.com/44675043/207128546-ece0a8a4-ebd0-4386-bd56-736c865e9801.png)

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/FloatActionButton.kt
>  import androidx.compose.material.icons.filled.Add
Нужно следить за пакетами, которые ты используешь. В общем случае после миграции на MD3 не должно быть ни одного импорта либы `androidx.compose.material` потому что это MD2, иначе происходит то, что произошло у тебя тут - `Icon` подтягивает не тот `LocalContentColor` и перестаёт соответствовать теме.

![image](https://user-images.githubusercontent.com/44675043/207120803-c3fdf0ba-f60a-4a14-82c6-e30927306959.png)

Это происходит и в карточках, и в диалогах. Пройдись по всем своим файлам и проделай эту операцию

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/FloatActionButton.kt
> -                        backgroundColor = colorResource(R.color.accent),
Табы
![image](https://user-images.githubusercontent.com/44675043/207121702-4161cacf-47f3-4f9f-b3d0-925581f1ce46.png)

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/FloatActionButton.kt
> +                                contentDescription = null
А чего ты решил убрать `contentDescription`? Пусть остаётся, если уже до этого было.

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/Devices.kt
> +			}
Почему?

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/DevicesViewModel.kt
>  ) : ViewModel() {
![image](https://user-images.githubusercontent.com/44675043/207123584-4da1c1c3-cdd7-4477-885a-08dadbbfe207.png)

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/DevicesViewModel.kt
> +    val uiDevices = _uiDevices.asSharedFlow()
Ты не понял. Этот флоу назывался `uiEvents` не потому что я скопировал его из событий и забыл, а потому что он существует буквально для событий пользовательского интерфейса - UI events. UI собирает эти события (успех, ошибка и т.д.) и отображает в снекбаре.

Переименуй назад плиз

2022-12-12 18:45 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/DeviceAcceptDialogContent.kt
>                                  )
Вместо ручного переопределения кнопки стоит использовать `PrimaryTextButton`, которая определена в `ru.rtuitlab.itlab.presentation.ui.components.PrimaryButton.kt`

2022-12-12 18:49 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/FloatActionButton.kt
>  import androidx.compose.material.icons.filled.Add
И вообще composable `FloatActionButton` нарушает идиоматику компоуза. Нет причины, по которой его нужно выделять в отдельный компонент, он всё равно используется только в одном месте. Его стоит удалить и прямо на месте вызова написать нужный код.

2022-12-17 18:33 UTC, MrApple100 commented
Сделаль

2022-12-17 19:11 UTC, CalamityDeadshot reviewed
Ещё вместо своих `OutlinedTextField`ов нужно использовать `OutlinedAppTextField`, который уже правильно стилизован. Т.е. вместо этого 
![image](https://user-images.githubusercontent.com/44675043/208259196-e73e3245-f918-48cc-9438-4a2e51e657a1.png)
Должно быть это
![image](https://user-images.githubusercontent.com/44675043/208259521-29149c2f-b571-4911-a458-12f65a2f6636.png)

2022-12-17 19:11 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/devices/components/DeviceCard.kt
> +                        IconizedRow(painter = painterResource(R.drawable.ic_serial_number), contentDescription = stringResource(R.string.serial_number)) {
Не особо много смысла закидывать эту иконку в ресурсы. Это стандартная иконка MD, и она доступна по `Icons.Default.Article` как `ImageVector` (и на [сайте](https://fonts.google.com/icons?icon.query=Article&icon.platform=android&icon.set=Material+Icons)). Незачем раздувать вес приложения.

Добавлять иконку напрямую в ресурсы надо только тогда, когда её нет в `Icons.Default.*`. То же самое для остальных иконок, которые ты добавил в ресурсы.

И возьми плиз в привычку проверять, как это выглядит в других темах. А то у нас во всём приложении в карточках иконки с альфой 0.6 или выше (первый пик), а у тебя 0.3 (второй пик).
![image](https://user-images.githubusercontent.com/44675043/208257222-10ab88ba-ff9e-4b7e-987c-decc229d95fc.png)

![image](https://user-images.githubusercontent.com/44675043/208257003-c53f0c5e-a7ca-4106-81df-4ab10df59596.png)
Можешь поменять дефолтую альфу в `IconizedRow` для `Painter` на 0.6 (но убедись, что после этого всё приложение выглядит так же), либо передать аргументом, но лучше используй `IconizedRow` для `ImageVector`, передавая туда иконки из стандартной библиотеки.

2022-12-17 20:34 UTC, MrApple100 commented
Сделано

2022-12-26 12:09 UTC, CalamityDeadshot commented
> Сделано

Поля ввода неправильно выглядят
![image](https://user-images.githubusercontent.com/44675043/209547408-b46dea09-537b-473e-94e5-4094623cd35d.png)

2022-12-26 12:26 UTC, MrApple100 commented
Как оно может быть неправильным если дизайна
 даже для этого элемента в технике нет

2022-12-26 16:29 UTC, CalamityDeadshot commented
Так, что он есть для всего приложения, и везде должен выглядеть одинаково.
Ты забыл своё переопределение цветов для `OutlinedAppTextField` убрать
![image](https://user-images.githubusercontent.com/44675043/209567754-40b94618-feb6-42ac-9001-15ec07f1799a.png)

2022-12-28 11:30 UTC, merged