FilePage in reports to MD3
RTUITLab/ITLab-Android pull request #31
Opened 2022-12-11 16:02 UTC by MrApple100

2022-12-12 19:04 UTC, CalamityDeadshot requested changes
Файлы по дизайну должны стать отдельным экраном, а не вкладкой в отчётах.

2022-12-12 19:04 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/micro_file_service/FilesViewModel.kt
> +    }
Из-за того, что `fetchFiles` запускает свою корутину, `_isRefreshing` обновляется в `false` сразу после вызова `fetchFiles`, а не завершения запроса.

2022-12-17 18:34 UTC, MrApple100 commented
И это тоже сделаль

2022-12-17 19:50 UTC, CalamityDeadshot reviewed
Файлы не загружаются при первом открытии экрана, надо руками обновить.

2022-12-17 19:50 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/micro_file_service/FilesViewModel.kt
> +    val filesResponse = _filesResponse.asStateFlow().also { fetchFiles() }
Не надо так делать, я писал об этом в предыдущих ревью. Этому место в `init`

2022-12-17 19:50 UTC, CalamityDeadshot commented on app/src/main/java/ru/rtuitlab/itlab/presentation/screens/files/BaseElements.kt
>  fun BaseElements(
Пора бы переименовать уже

2022-12-17 20:33 UTC, MrApple100 commented
Так? Я понимаю, что при перезаходе на другой акк, данные должны поменяться. Но я не до конца понимаю где находится логика обновления состояния пользователя. Я увидел аналог, вроде он

2022-12-20 17:37 UTC, CalamityDeadshot commented
> Так? Я понимаю, что при перезаходе на другой акк, данные должны поменяться. Но я не до конца понимаю где находится логика обновления состояния пользователя. Я увидел аналог, вроде он

Я потратил время, чтобы исправить все связанные с перезаходом проблемы. Теперь существует `LoginActivity`, которая незаметно меняется с `MainActivity`, поэтому вью модели при выходе уничтожаются, и информация пользователя не сохранятется от сессии к сессии.

Я написал `collectUntil` не для этого, а для создания во вью моделях контракта, что во `flow`, к которому `collectUntil` применяется, во-первых что-то есть, а во-вторых это что-то соответствует какому-то условию - только тогда что-то делается.

Например, в `ReportsViewModel` нужно загрузить все отчёты вместе с зарплатами. Сервер отдаёт отчёты основываясь на клеймах пользователя, поэтому если пользователь админ, загрузятся все доступные ему отчёты (в будущем это позволит максимально быстро внедрить функционал админа, если будет нужно), но зарплаты можно загрузить **только** по ID пользовтеля, поэтому в момент запроса этот ID необходим. Именно это проверяет `currentUserId.collectUntil()`, потому что у андройда может случиться инсульт, и он не отдаст этот ID вовремя, и приложение вылетит.
```kotlin
init {
    viewModelScope.launch {
        currentUserId.collectUntil(
            condition = { it != null },
            action = {
                it?.let {
                    launch {
                        updateReports.firstTime(
                            userId = it,
                            refreshState = _isRefreshing,
                            onError = {
                                launch {
                                    _uiEvents.emit(UiEvent.Snackbar(it))
                                }
                            }
                        )
                    }
                }
            }
        )
    }
}
```

В твоём случае это не нужно, потому что `fetchFiles(userId = null)` получит файлы по клеймам. 
Говоря это
> Не надо так делать, я писал об этом в предыдущих ревью. Этому место в `init`  

Я хотел, чтобы ты просто поместил вызов `fetchFiles()` в `init`, чтобы не охотиться потом на места, где оно через `also` вызывается.
Т.е.
```kotlin
init {
    fetchFiles()
}
```

2022-12-26 12:18 UTC, CalamityDeadshot commented
Файлы всё ещё не загружаются при открытии экрана, хотя в логах видно запрос
![image](https://user-images.githubusercontent.com/44675043/209547842-8cd1b515-0c34-404c-85d3-5a2292535df6.png)
![image](https://user-images.githubusercontent.com/44675043/209548201-dd271e04-26ea-4d2e-85d2-f4633255387d.png)

2022-12-26 12:49 UTC, MrApple100 commented
Тип я поэтому и сделал как было в прошлом варианте. А если просто написать fetch то фиг. Я меняю обратно?

2022-12-28 09:59 UTC, merged